### PR TITLE
patch: changed logo to rounded in linux and windows

### LINKED ISSUE #1714: Use rounded icon on Windows, Linux
In #1438 we made a nice rounded icon. Let's use it on Linux and Windows too! 

A user reported that the square edge icon looks weird amongst other rounded icons in their system tray.

### PR DESCRIPTION
**Pull request by rajdip-b**
### Pull Request Checklist

- [x] I have linked this PR to related GitHub issue.
- [x] I have updated the CHANGELOG.md file with relevant changes (the file is located at the root of monorepo).

Fixes #1714

Please ensure you completed the following checks if you did any changes to the mobile package:

- [ ] I have run e2e tests for mobile
- [ ] I have updated base screenshots for visual regression tests

### CODE REVIEW

**Review by holmesworcester — APPROVED** [review]

**Comment by EmiM** [comment]
@rajdip-b could you merge current develop to your branch? Linter check is failing and it'll probably be resolved after that.
We'd love to merge your changes :)

**Comment by rajdip-b** [comment]
Hey @EmiM , its on its way

**Comment by rajdip-b** [comment]
@EmiM hey, there might be some issues with the `CHANGELOG.md` file. I don't exactly recall which version I added the rounded logos to, so that line might be misplaced. Can you inspect the changes and lmk if its okay or not?

**Comment by EmiM** [comment]
@rajdip-b thanks! Generally it should go under [unreleased] on the top of the changelog file because [unreleased] changes to [version] as we release new version.

Did you select "Allow edits from maintainers" when creating MR? If not, you could do that with the next MRs so we don't have to bother you with stuff like "pls merge develop to your branch".
https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork

**Comment by rajdip-b** [comment]
>> Generally it should go under [unreleased] on the top of the changelog file because [unreleased] changes to [] as we release new version.

making the changes now!

>> If not, you could do that with the next MRs so we don't have to bother you with stuff like "pls merge develop to your branch".

It's absolutely okay by me! I believe it's the contributors' responsibility to make a PR complete in its entirety!

**Comment by rajdip-b** [comment]
@EmiM there you go!

**Pull request merged**
