### PR TITLE
Chore/replace disabling inputs with splash

### PR DESCRIPTION
**Pull request by siepra**
### Pull Request Checklist

- [x] I have linked this PR to related GitHub issue.
- [x] I have updated the CHANGELOG.md file with relevant changes (the file is located at the root of monorepo).

### CODE REVIEW

**Comment by leblowl** [comment]
Why are tests being moved to the __tests__ directory?

**Comment by siepra** [comment]
We don't really have any strict policy on tests location. I decided to use `toMatchSnapshot`instead of the inline one, because the snapshot is very long and it makes the test harder to read. At the same time I thought that moving it to a separate directory will make the whole component directory less messy

**Review by Kacper-RF — COMMENTED** [review]
Could you leave the version information on the splash screen until there is an "About" tab in mobile settings where the user can see the current version? I think this is important for QA and future debugging purposes.

**Comment by leblowl** [comment]
idea: I might squash commits to keep the git history on develop a little cleaner/easier to undo

**Comment by siepra** [comment]
@leblowl I always squash, although recently I've been thinking about some more strict naming policy like prefixes etc.

**Review by Kacper-RF — APPROVED** [review]

**Comment by leblowl** [comment]
@siepra nice, naming policy for commits? Like https://www.conventionalcommits.org/en/v1.0.0/?

**Pull request merged**
