### PR TITLE
Add support for multi-line message (desktop)

### PR DESCRIPTION
**Pull request by josephlacey**
Fix for #1087.  There's a slight refactor in the relevant code to reduce some redundancy.  Let me know if there's anything missing here or whether there's a commit standard I need to follow.

### CODE REVIEW

**Comment by holmesworcester** [comment]
@josephlacey thanks! 

To respond to the question you asked in Quiet, I don't think we have any code standard documentation beyond linters passing, but I may be wrong about that.

Typically we have a rule that new features come with tests to prove they work, but this is just a few lines of code change and I'm not sure what the most appropriate test would be. Ideally we'd have a test that when the user does shift+enter a message is not sent, and that they can create a message with multiple lines.  

@EmiM is there anything you'd like to see here before merging?

**Comment by holmesworcester** [comment]
Just in case you miss my message in Quiet, you can ignore the failing chromatic tests, windows builds, and mac builds since we're working on those.

**Comment by josephlacey** [comment]
Fixed linting error and added Cypress test for the multiline feature.

**Comment by EmiM** [comment]
@josephlacey linter check is not passing - multi-line rule in cypress test.

**Comment by josephlacey** [comment]
> @josephlacey linter check is not passing - multi-line rule in cypress test.

@holmesworcester Haha indeed.  I mean technically the linter is correct; it does contain multiline text.  But that's exactly what we're testing.  I couldn't get the Cypress test to pass by including line break shorthand, but maybe I just need to dig into the documentation for that a little more.

**Comment by josephlacey** [comment]
I might be able to restructure the test to watch the shift+enter keydown rather than the state of the input after the keydown.  Again I'll take a look.

**Comment by holmesworcester** [comment]
Heh that's hilarious. If there's a way to introduce a linter exception here or escape it we could do this too. Not sure how that works!

**Comment by josephlacey** [comment]
The included line break wasn't required for the test to pass, so I just removed it.

**Comment by josephlacey** [comment]
It looks I accidentally closed this with an attempt to rename the branch.  Reopening.

**Comment by siepra** [comment]
@josephlacey I see chromatic deployment did not pass. Please run storybook (`cd packages/desktop && npm run storybook`) and see which component doesn't render and why

**Comment by siepra** [comment]
Also as we mainly use cypress tests for checking scroll-regressions, maybe it's better to put the test for breaking lines in rtl tests for channel? (`packages/desktop/src/rtl-tests/channel.test.tsx`)

It should do something like
```await userEvent.type(messageInput, '{enter}')```
and then expect the message not to be in the store

But of course this cypress test you provided seems fine

**Comment by josephlacey** [comment]
@siepra Thanks for the feedback, here.

> @josephlacey I see chromatic deployment did not pass. Please run storybook (`cd packages/desktop && npm run storybook`) and see which component doesn't render and why

The reported error in GitHub Actions is `Missing project token`, which seems like the test didn't have everything it needed to run rather than the test failing.  I'm new to Storybook though, so I'm not sure, but could this be a permission issue with GitHub Secrets?  It looks like all my commits are failing with the same error.

> Also as we mainly use cypress tests for checking scroll-regressions, maybe it's better to put the test for breaking lines in rtl tests for channel? (`packages/desktop/src/rtl-tests/channel.test.tsx`)

Sure, I can change the test to keep it consistent.  Should I write an entirely new one or added this feature to an existing one?

**Comment by Kacper-RF** [comment]
@josephlacey Could You merge newest develop branch to Your branch ?

**Comment by josephlacey** [comment]
> @josephlacey Could You merge newest develop branch to Your branch ?

Done

**Comment by josephlacey** [comment]
> @josephlacey Could You merge newest develop branch to Your branch ?

@Kacper-RF Done.

**Comment by josephlacey** [comment]
> I see chromatic deployment did not pass. Please run storybook (`cd packages/desktop && npm run storybook`) and see which component doesn't render and why

Manually deployed regression test while the automated ones are debugged,

https://www.chromatic.com/build?appId=62021a6b9c4ef3003ab65846&number=1349

Currently shows as passing.

**Comment by Kacper-RF** [comment]
@josephlacey Thanks !
I also found solution for problems with CI with Chromatic, now as You are collaborator, You have to create standard pull request with these features(not form fork) and then it should be working. Unfortunately secrets for actions are not passed to workflows which are triggered by pull request from fork.

**Comment by Kacper-RF** [comment]
@josephlacey I already merged this PR, because we want to create new alpha release for QA session today.

**Comment by josephlacey** [comment]
> @josephlacey Thanks ! I also found solution for problems with CI with Chromatic, now as You are collaborator, You have to create standard pull request with these features(not form fork) and then it should be working. Unfortunately secrets for actions are not passed to workflows which are triggered by pull request from fork.

Thanks @Kacper-RF.  Interesting nuance about forks, ok.  I'll submit direct PR's going forward.

**Pull request merged**
