### PR TITLE
Fix/tweak settings designs (#2537)

### PR DESCRIPTION
**Pull request by mike-kiss**
This PR:
- Switches the channel settings menu over to using a Drawer component
- Adds a README.md to establish UI development practices on the desktop app

### Pull Request Checklist

- [x] I have linked this PR to a related GitHub issue. https://github.com/TryQuiet/quiet/issues/2537
- [x] I have added a description of the change (and Github issue number, if any) to the root [CHANGELOG.md](https://github.com/TryQuiet/quiet/blob/develop/CHANGELOG.md).

### (Optional) Mobile checklist

Please ensure you completed the following checks if you did any changes to the mobile package:

- [ ] I have run e2e tests for mobile
- [ ] I have updated base screenshots for visual regression tests

### CODE REVIEW

**Comment by mike-kiss** [comment]
Light Mode: 
image
image
image

Dark mode:
image
image
image

**Comment by holmesworcester** [comment]
@jgaylor do you have any feedback on these screenshots? (this is mike's adaptation of the new mobile-style settings designs for desktop.)

**Comment by jgaylor** [comment]
Thanks for sharing this. Here are some quick thoughts:

Dark/light mode: Overall, it looks good except for the radio buttons and the visibility icon. For icons, we should probably use grayscale. For radios in dark mode, the colors should be reversed, but that would be temporary anyway based on my comments later...

Panels: It's difficult to tell if they all have the same width since the screenshots are at various zoom levels, but they should if not.

Additionally, we're mixing existing content layout with the new drawer, so there's no clear guide for how that should look. And design should layout this view in the new system. For example, the Notifications drawer needs a design that matches our new convention (action row with a checkmark).

Holmes mentioned this will be on a branch soon, which will make it easier for me to review in more detail.

**Comment by islathehut** [comment]
Code looks good but we should fix the desktop tests.  That should just require updating snapshots.

**Review by islathehut — APPROVED** [review]
Approved.  We can alter the length of the hidden invite link to fit the drawer now or later, doesn't matter to me.

**Pull request merged**
