### PR TITLE
Remove registration attempts selector

### PR DESCRIPTION
**Pull request by vinkabuki**
### Pull Request Checklist

- [ ] I have linked this PR to related GitHub issue.
- [x] I have updated the CHANGELOG.md file with relevant changes (the file is located at the root of monorepo).

### CODE REVIEW

**Comment by leblowl** [comment]
Looks good to me, I am curious, why are we removing the registration attempts?

**Comment by vinkabuki** [comment]
image

**Comment by leblowl** [comment]
Just a reminder that I think squashing would be helpful

**Comment by kingalg** [comment]
quiet@2.0.3-alpha.0

I can't check it but as per discussion with @vinkabuki he confirmed that it's done.

**Pull request merged**
