### PR TITLE
Feat/519 big emoji messages

### PR DESCRIPTION
**Pull request by mike-kiss**
### Pull Request Checklist

- [x] I have linked this PR to a related GitHub issue.
- [x] I have added a description of the change (and Github issue number, if any) to the root [CHANGELOG.md](https://github.com/TryQuiet/quiet/blob/develop/CHANGELOG.md).

### (Optional) Mobile checklist

Please ensure you completed the following checks if you did any changes to the mobile package:

- [ ] I have run e2e tests for mobile
- [ ] I have updated base screenshots for visual regression tests

### CODE REVIEW

**Comment by mike-kiss** [comment]
The desktop test failures appear to be a result of the MUI auto-generated class names changing in the snapshots. I can investigate but I don't think this is actually the result of my changes - do we have a solution for this? (Edit to add: do we have control over the text colors for the snapshot diffs? I find these very hard to read)

image

**Comment by leblowl** [comment]
Thanks @mike-kiss , I think the test failures are from changing the className prop. I don't see them failing on develop. I'm not sure if there is another solution, but I have just been updating the snapshots in these cases.

**Comment by leblowl** [comment]
Also, I'm not sure about the color, but I agree that would be nice to change

**Comment by mike-kiss** [comment]
KK. Snapshots updated. Should pass now, I hope :+1:

**Comment by holmesworcester** [comment]
Thanks @mike-kiss!

**Comment by mike-kiss** [comment]
Still seeing errors on some the tests but these look like network/DNS-level issues

**Review by leblowl — APPROVED** [review]
Thanks!

**Pull request merged**
