### PR TITLE
Remove electron-log from logger

### PR DESCRIPTION
**Pull request by siepra**

### CODE REVIEW

**Comment by EmiM** [comment]
I don't really like removing this completely because I sometimes use this feature while debugging with Kinga. There is no other way?

**Comment by holmesworcester** [comment]
I'm okay with removing this if we have an issue for adding it back.

**Comment by Dinek007** [comment]
> I'm okay with removing this if we have an issue for adding it back.



> I'm okay with removing this if we have an issue for adding it back.

yes, im working on it

**Comment by siepra** [comment]
Due to problem with CI cache, changes were moved to another PR https://github.com/TryQuiet/quiet/pull/807

**Pull request closed without merging**
