### PR TITLE
fix: updating channel name creation logic

### PR DESCRIPTION
**Pull request by richardtorres314**
### Pull Request Checklist

- [x] I have linked this PR to related GitHub issue.  #2215
- [x] I have updated the CHANGELOG.md file with relevant changes (the file is located at the root of monorepo).

### (Optional) Mobile checklist

Please ensure you completed the following checks if you did any changes to the mobile package:

- [ ] I have run e2e tests for mobile
- [ ] I have updated base screenshots for visual regression tests

## Before
Before

## After
After

### CODE REVIEW

**Comment by leblowl** [comment]
Thanks @richardtorres314 

@holmesworcester I'm happy to merge this as I think it's an improvement, but do we also want an error message in the case where someone provides ".-.-." as a channel name? Currently it looks like the channel must be non empty and cannot start with a space or hyphen. Then for common special characters (like & and .), these get stripped from the channel name and it's not an error. So if we put a channel name like ".-.-." it doesn't start with a dash or space, so it strips the periods and then removes the hyphens and there is no error but it also doesn't allow you to add the channel name because once the hyphens and periods are stripped the channel name is empty.

One easy approach is just provide an error if someone includes special characters, rather than getting fancy and stripping them out.

**Comment by holmesworcester** [comment]
Errors really break the flow though. We should find a library or an open source example for validation in this case and use that. Or enumerate all the cases here, but it's easy to miss one!

**Comment by richardtorres314** [comment]
@holmesworcester totally agree! I could see many cases not covered in our current tests that could lead to this logic needing constant patching.

@leblowl would you happen to know what cases we do/don't want covered? I've found alternatives mentioning that "Channel names have a 21-character limit and can include lowercase letters, non-Latin characters, numbers, and hyphens". Is this similar naming convention we're adopting? Thank you!

**Comment by leblowl** [comment]
@holmesworcester In case there is a misunderstanding, to me it looks like there is still an error in the case of `.-.-.` (the user cannot add a channel with that name), however there is no error message. So do we want a case where the user enters a channel name, doesn't receive any feedback and yet cannot create a channel with that name? I'm happy with however ya'll would like it to be, but just wanted to mention that.

@richardtorres314 I'm not really sure. I'd probably ask @holmesworcester

**Comment by holmesworcester** [comment]
The thing we want to achieve with usernames is uniqueness and some resistance to spoofing usernames with homograph attacks. I think this is less important for channels,  but we decided it would be easiest to use the same validation for now.

We don't want someone to be able to use leading or trailing spaces to spoof a username.

And because the onboarding experience is such a sensitive moment, we don't want to frustrate the user with restrictions that are hard to understand. This is why replacing spaces with hyphens is nice. GitHub uses this approach for repo names, IIRC. In the same spirit, a situation where a user enters some text and gets neither an error nor an automatically modified entry (e.g. hyphens for spaces) is not a good one.

I think these are the only requirements, but I'm happy using something more restrictive too if there's something off the shelf that's easy.

**Comment by richardtorres314** [comment]
@holmesworcester Totally agree with the lack of error messaging! I noticed this was the same experience when a channel name consisted of only special characters: no error yet no channel created (see screenshot below).

Errorless Channel Creation

I'll create an issue for this and move this to the top of my list. Let me know if any additional changes are needed. Thank you!

**Comment by holmesworcester** [comment]
I think creating an issue merging this is a good way! Fwiw, special characters could be turned into hyphens too.

**Pull request merged**
