### PR TITLE
Markdown implementation

### LINKED ISSUE #1088: User can use basic markdown
Jason and I decided we should use other open source apps as inspiration for styles. For example https://github.com/mattermost/

It should look good on desktop and mobile, which means finding libraries for both React and React Native. 

Related to #1025 

The most important thing is that `this` should work and 

```
this...
should work
````

Slack does not implement "#" and "##" and "------" for H1, H2, etc and I think we should also not do this.

Bold and `[link](https://link.com)` should work too.

### PR DESCRIPTION
**Pull request by josephlacey**
WIP Fixes #1088

### CODE REVIEW

**Comment by vinkabuki** [comment]
@josephlacey Hey, what is the status of this? Do you need any support?

**Comment by josephlacey** [comment]
> @josephlacey could you merge develop into your branch? CI fix is there. Right now we can't see if checks pass.

@EmiM I'll push this merge, sure, but several of the tests are still failing and I have a question about resolving some of them.  I'll work on the scrolling regression issue, but last week I posted a question about one of the testing issues related to the libraries on the feature issue here.  https://github.com/TryQuiet/quiet/issues/1088#issuecomment-1585153933

**Comment by josephlacey** [comment]
@EmiM The scroll regression tests were failing because the `*` used in two of the base images converted the text to italics per the Markdown spec.

after launch-base

I've updated the base images to reflect the new text handling,

after launch-actual

I've also manually pushed the Chromatic tests.  It looks like there are several UI approvals needed for the same issue.  The testing images include `*`, so the text is being converted to italics.  Let me know if you want me to approve them.

And for the failing Desktop and Mobile tests, let me know the preferred way forward to solve those.  Further details here, https://github.com/TryQuiet/quiet/issues/1088#issuecomment-1585153933

**Comment by vinkabuki** [comment]
https://github.com/TryQuiet/quiet/pull/1652 <- Here are my fixes for failing tests, @josephlacey I've created new branch based on your work as it was easier for me.

**Pull request merged**
