### PR TITLE
Updating channel naming logic

### LINKED ISSUE #2299: Channel creation should show error message if channel cannot be created
Currently, when a channel cannot be created because the channel name does not meet requirements (e.g. contains only special characters), the user does not receive an error message but is not able to create a channel (see below).

Errorless Channel Creation

The proposed fix is to add an error message in those cases.

### PR DESCRIPTION
**Pull request by richardtorres314**
### Pull Request Checklist

- [x] I have linked this PR to a related GitHub issue.
- [x] I have added a description of the change (and Github issue number, if any) to the root [CHANGELOG.md](https://github.com/TryQuiet/quiet/blob/develop/CHANGELOG.md).

### (Optional) Mobile checklist

Please ensure you completed the following checks if you did any changes to the mobile package:

- [ ] I have run e2e tests for mobile
- [ ] I have updated base screenshots for visual regression tests

#### Before
Before

#### After
After

### CODE REVIEW

**Comment by leblowl** [comment]
Thanks @richardtorres314. It looks like a few tests fail. And then I was thinking about the case of channel names `Test` and `test`. It looks like we probably want our channel/username comparison to be case insensitive, so `Test === test` and it looks like it was previously. I think just adding the `toLowerCase()` back in there should resolve that.

**Comment by richardtorres314** [comment]
@leblowl I've updated a few of the tests but still have some outstanding failing tests I can't seem to resolve. I also can't seem to build the desktop app to test due to an error that seems to have been introduced a few days ago (error message: `Uncaught Error: You must pass a selector to useSelector`). I'll update this PR when I can rebase off of `develop` and building is resolved.

**Comment by holmesworcester** [comment]
@leblowl @EmiM can you reproduce develop being broken? 

@richardtorres314 can you add any information about your system to help us reproduce the problem if we cannot?

**Comment by richardtorres314** [comment]
@holmesworcester I just found my problem, I switched node environments when working on a different project and failed to revert environments when returning to the project. I can confirm upon switching that all errors have been removed and the app works as expected.

I'll continue working on the tests today. Thank you!

**Review by leblowl — APPROVED** [review]
Thanks!

**Pull request merged**
