### PR TITLE
remove global lerna dependency

### PR DESCRIPTION
**Pull request by tylerchilds**

### CODE REVIEW

**Comment by holmesworcester** [comment]
@vinkabuki @EmiM could one of you review this?

**Comment by siepra** [comment]
Doesn't this change force you to be in the project root folder to be able to bootstrap?

**Comment by vinkabuki** [comment]
@siepra I agree, but I think it's indeed a better practice to not install lerna globally, people who want to just clone it and try may by annoyed by this, devs will install lerna globally anyway for convenience.

**Comment by vinkabuki** [comment]
It's fine. we can optionally add a comment that it is very convenient to have lerna globally when you are actively working on a project

**Pull request merged**
