### PR TITLE
Fixes to caret line traversal

### PR DESCRIPTION
**Pull request by josephlacey**
Bug fixes for pasting multi-line text and handling empty lines traversal. #1339

### CODE REVIEW

**Comment by vinkabuki** [comment]
@josephlacey It looks like it's almost ready to review, isn't it?

**Comment by josephlacey** [comment]
> @josephlacey It looks like it's almost ready to review, isn't it?

@vinkabuki Looks like GitHub had a problem merging this branch because a previous iteration had been merged in.  I resolved that, so it is ready for review.

**Comment by josephlacey** [comment]
> @josephlacey desktop tests don't pass

These should be fixed now.  I've got into the bad habit of expecting failing test notices and not reading them carefully.  I'll be more vigilant about that going forward.

**Comment by josephlacey** [comment]
> @josephlacey desktop tests don't pass

@EmiM These should be fixed now.  I've got into the bad habit of expecting failing test notices and not reading them carefully.  I'll be more vigilant about that going forward.

The Visual regressions test always fails for me, but I've published to Chromatic manually.

**Pull request merged**
